services:
  - type: web
    name: ellie-voice-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python ellie_voice_app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
